# Jekyll Configuration

url: http://scgy5555.github.io/
title: scgy5555的个人博客
description: 个人技术博客
author: scgy5555
email: scgy5555@qq.com
baseurl: /

auto: false
lsi: false
pygments: false
server_port: 4000
markdown: maruku

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex